apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  labels:
    name: {{ name }}
spec:
  selector:
    name: {{ name }}
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  type: NodePort
