apiVersion: v1
kind: Pod
metadata:
  name: k8s-e2e
spec:
  containers:
  - image: k8s-e2e
    name: k8s-e2e
    env:
    - name: E2E_REPORT_DIR
      value: /reports
    - name: API_SERVER
      value: ${API_SERVER}
    - name: FOCUS
      value: "Load capacity"
    volumeMounts:
      - mountPath: /reports
        name: job-params
  restartPolicy: Never
  volumes:
    - hostPath:
        path: /var/lib/volumes/e2e-test/10_nodes
      name: job-params