configs:
  private_interface: p1p1.602
  public_interface: p1p1.602
  ingress:
    enabled: true
  glance:
    tls:
      enabled: false
    bootstrap:
      enable: true
  neutron:
    tls:
      enabled: false
    physnets:
      - name: "physnet1"
        bridge_name: "br-external"
        interface: "bond0.648"
        flat: true
        vlan_range: false
        dpdk: false
    bootstrap:
      internal:
        enable: true
      external:
        enable: true
        net_name: ext-net
        subnet_name: ext-subnet
        physnet: physnet1
        network: 172.20.172.0/22
        gateway: 172.20.172.1
        nameserver: 8.8.8.8
        pool:
          start: 172.20.173.0
          end: 172.20.175.254
  keystone:
    debug: true
  security:
    tls:
      create_certificates: false
  etcd:
    tls:
      enabled: false
  db:
    tls:
      enabled: false
  rabbitmq:
    tls:
      enabled: false
  keystone:
    tls:
      enabled: false
  cinder:
    tls:
      enabled: false
  heat:
    tls:
      enabled: false
  nova:
    tls:
      enabled: false
  horizon:
    tls:
      enabled: false

